name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Run every 12 hours

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: zenitsudono
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=blue&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
          
          # Custom settings for a unique look
          color_snake: "#64a1f4"  # Custom blue color for the snake
          color_dots: "#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9"  # Different shades of blue for contributions
          bg_color: "#ffffff00"  # Transparent background

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
